# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:29:54+00:00

from __future__ import annotations

from datetime import date
from typing import Any, List, Optional

from pydantic import BaseModel, RootModel


class AlternateImage(BaseModel):
    height: Optional[int] = None
    id: Optional[int] = None
    name: Optional[str] = None
    url: Optional[str] = None
    width: Optional[int] = None


class ExtendedAttribute(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    value: Optional[str] = None


class Language(BaseModel):
    id: Optional[int] = None
    isActive: Optional[bool] = None
    isoCode: Optional[str] = None
    name: Optional[str] = None


class MediaTypeHolder(BaseModel):
    description: Optional[str] = None
    name: Optional[str] = None


class Message(BaseModel):
    errorCode: Optional[str] = None
    errorDetail: Optional[str] = None
    errorMessage: Optional[str] = None
    userMessage: Optional[str] = None


class Pagination(BaseModel):
    count: Optional[int] = None
    currentUrl: Optional[str] = None
    max: Optional[int] = None
    nextUrl: Optional[str] = None
    offset: Optional[int] = None
    pageNum: Optional[int] = None
    previousUrl: Optional[str] = None
    sort: Optional[str] = None
    total: Optional[int] = None
    totalPages: Optional[int] = None


class ResourceWrapped(RootModel[Any]):
    root: Any


class Source(BaseModel):
    acronym: Optional[str] = None
    contactEmail: Optional[str] = None
    id: Optional[int] = None
    largeLogoUrl: Optional[str] = None
    name: Optional[str] = None
    smallLogoUrl: Optional[str] = None
    websiteUrl: Optional[str] = None


class SyndicateMarshaller(BaseModel):
    content: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    sourceUrl: Optional[str] = None


class TagLanguageMarshaller(BaseModel):
    id: Optional[int] = None
    isActive: Optional[bool] = None
    isoCode: Optional[str] = None
    name: Optional[str] = None


class TagTypeMarshaller(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class TwitterAccount(RootModel[Any]):
    root: Any


class YoutubeMetadata(BaseModel):
    pass


class Test(RootModel[Any]):
    root: Any


class Campaign(BaseModel):
    contactEmail: Optional[str] = None
    description: Optional[str] = None
    endDate: Optional[date] = None
    id: Optional[int] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    startDate: Optional[date] = None


class Collection(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None


class Html(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None


class Image(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    height: Optional[int] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None
    width: Optional[int] = None


class Infographic(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    height: Optional[int] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None
    width: Optional[int] = None


class MediaItem(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None


class Meta(BaseModel):
    messages: Optional[List[Message]] = None
    pagination: Optional[Pagination] = None
    status: Optional[int] = None


class MetaWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Meta]] = None


class PDF(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None


class PDFWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[PDF]] = None


class PaginationWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Pagination]] = None


class SourceWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Source]] = None


class SyndicateMarshallerWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[SyndicateMarshaller]] = None


class TagLanguageMarshallerWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[TagLanguageMarshaller]] = None


class TagMarshaller(BaseModel):
    id: Optional[int] = None
    language: Optional[TagLanguageMarshaller] = None
    name: Optional[str] = None
    type: Optional[TagTypeMarshaller] = None


class TagMarshallerWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[TagMarshaller]] = None


class TagTypeMarshallerWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[TagTypeMarshaller]] = None


class Tweet(BaseModel):
    account: Optional[TwitterAccount] = None
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    mediaUrl: Optional[str] = None
    messageText: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None
    tweetDate: Optional[date] = None
    tweetId: Optional[int] = None
    videoVariantUrl: Optional[str] = None


class TweetWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Tweet]] = None


class Video(BaseModel):
    campaigns: Optional[List[Campaign]] = None
    createdBy: Optional[str] = None
    customAttributionUrl: Optional[str] = None
    customPreviewUrl: Optional[str] = None
    customThumbnailUrl: Optional[str] = None
    dateContentAuthored: Optional[date] = None
    dateContentPublished: Optional[date] = None
    dateContentReviewed: Optional[date] = None
    dateContentUpdated: Optional[date] = None
    dateSyndicationCaptured: Optional[date] = None
    dateSyndicationUpdated: Optional[date] = None
    dateSyndicationVisible: Optional[date] = None
    description: Optional[str] = None
    extendedAttributes: Optional[List[ExtendedAttribute]] = None
    externalGuid: Optional[str] = None
    foreignSyndicationAPIUrl: Optional[str] = None
    hash: Optional[str] = None
    id: Optional[int] = None
    language: Optional[Language] = None
    mediaType: Optional[str] = None
    name: Optional[str] = None
    source: Optional[Source] = None
    sourceUrl: Optional[str] = None
    targetUrl: Optional[str] = None


class VideoWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Video]] = None


class YoutubeMetadataWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[YoutubeMetadata]] = None


class AlternateImageWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[AlternateImage]] = None


class CampaignWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Campaign]] = None


class CollectionWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Collection]] = None


class ExtendedAttributeWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[ExtendedAttribute]] = None


class HtmlWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Html]] = None


class ImageWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Image]] = None


class InfographicWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Infographic]] = None


class LanguageWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Language]] = None


class MediaItemWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[MediaItem]] = None


class MediaTypeHolderWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[MediaTypeHolder]] = None


class MessageWrapped(BaseModel):
    callback: Optional[str] = None
    meta: Optional[Meta] = None
    results: Optional[List[Message]] = None
