# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:29:54+00:00

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel

from . import MediaItem


class JsonGetResponse(RootModel[List[MediaItem]]):
    root: List[MediaItem] = Field(..., title='ArrayOfMediaItems')
