# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:29:54+00:00

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel

from . import TagLanguageMarshallerWrapped


class FieldFormatGetResponse(RootModel[List[TagLanguageMarshallerWrapped]]):
    root: List[TagLanguageMarshallerWrapped] = Field(..., title='ArrayOfTagLanguages')
