# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:29:54+00:00

from __future__ import annotations

from pydantic import BaseModel


class JpgGetResponse(BaseModel):
    pass
