# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:29:54+00:00

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel

from . import MediaItemWrapped


class FieldFormatGetResponse(RootModel[List[MediaItemWrapped]]):
    root: List[MediaItemWrapped] = Field(..., title='ArrayOfMediaItems')
